export const pets = [
  {
    id: 1,
    age: 1,
    petName: "prueba1",
    race: { description: "pastor aleman" },
    size: "pequeño",
    user: { id: 1 },
    vaccinationPlan: "ningun",
    careToHave: "aaaaa",
    aula: {id: 1},
    status: "aprovado"
  },
  {id: 2,
    age: 2,
    petName: "prueba2",
    race: { description: "pastor aleman" },
    size: "pequeño",
    user: { id: 2 },
    vaccinationPlan: "ningun",
    careToHave: "aaaaa",
    aula: {id: 2},
    status: "aprovado"},
  {id: 3,
    age: 3,
    petName: "prueba3",
    race: { description: "pastor aleman" },
    size: "pequeño",
    user: { id: 3 },
    vaccinationPlan: "ningun",
    careToHave: "aaaaa",
    aula: {id: 3},
    status: "aprovado"},
];
